
language: python
python:
  - "3.6"

# command to install dependencies
install: 
  - "pip install -U pip wheel"
  - "pip install -r requirements/developments.txt "

cache:
  directories:
      - $HOME/.cache/pip

# command to run tests
script: pytest -s -v

after_success:
    - coveralls
