
language: python
python:
  - "3.6"

# command to install dependencies
install: 
  - "pip install -U pip wheel"
  - "pip install -r requirements/developments.txt "

# command to run tests
script: pytest -s -v
