
language: python
python:
  - "3.6"

# command to install dependencies
install: 
  - "pip install -U pip wheel"
  - "pip install -r requirements/developments.txt "

cache:
  directories:
     - $HOME/.cache/pip

# command to run tests
script: 
    - pylint src/
    - pytest -s -v --cov=src --cov-report html

after_success:
    - coveralls
